2025-06-26 13:14:53,195 - app - INFO - 用户 admin 登录成功。
2025-06-26 13:14:53,226 - app - INFO - 用户 admin 成功加载首页。
2025-06-26 13:14:57,030 - app - INFO - 用户 admin 正在查看个人资料页面。
2025-06-26 13:15:06,352 - app - INFO - 用户 admin 成功加载首页。
2025-06-26 13:16:11,319 - app - INFO - 用户 admin 已登出。
2025-06-26 13:16:29,692 - app - INFO - 新用户 admin1 (角色: ADMIN) 注册成功。
2025-06-26 13:16:35,718 - app - INFO - 用户 admin1 登录成功。
2025-06-26 13:16:35,739 - app - INFO - 用户 admin1 成功加载首页。
2025-06-26 13:18:07,914 - app - INFO - 用户 admin1 成功加载首页。
2025-06-26 13:18:07,924 - app - ERROR - 加载首页时发生错误: Could not build url for endpoint 'admin_user.user_list'. Did you mean 'user.register' instead?
Traceback (most recent call last):
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/views/main_views.py", line 64, in index
    return render_template(
        "main/index.html",
    ...<2 lines>...
        cumulative_sales=cumulative_sales
    )
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/templates/main/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/templates/base.html", line 37, in top-level template code
    <a class="nav-link" href="{{ url_for('admin_user.user_list') }}">用户管理</a>
    
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin_user.user_list'. Did you mean 'user.register' instead?
2025-06-26 13:18:14,706 - app - INFO - 用户 admin1 成功加载首页。
2025-06-26 13:18:14,707 - app - ERROR - 加载首页时发生错误: Could not build url for endpoint 'admin_user.user_list'. Did you mean 'user.register' instead?
Traceback (most recent call last):
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/views/main_views.py", line 64, in index
    return render_template(
        "main/index.html",
    ...<2 lines>...
        cumulative_sales=cumulative_sales
    )
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/templates/main/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/templates/base.html", line 37, in top-level template code
    <a class="nav-link" href="{{ url_for('admin_user.user_list') }}">用户管理</a>
    
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin_user.user_list'. Did you mean 'user.register' instead?
2025-06-26 13:18:14,961 - app - INFO - 用户 admin1 成功加载首页。
2025-06-26 13:18:14,962 - app - ERROR - 加载首页时发生错误: Could not build url for endpoint 'admin_user.user_list'. Did you mean 'user.register' instead?
Traceback (most recent call last):
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/views/main_views.py", line 64, in index
    return render_template(
        "main/index.html",
    ...<2 lines>...
        cumulative_sales=cumulative_sales
    )
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/templates/main/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/app/templates/base.html", line 37, in top-level template code
    <a class="nav-link" href="{{ url_for('admin_user.user_list') }}">用户管理</a>
    
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/Users/renweimin/PycharmProjects/FlaskProject/MXStoreBI/.venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin_user.user_list'. Did you mean 'user.register' instead?
2025-06-26 13:19:16,919 - app - INFO - 用户 admin1 成功加载首页。
2025-06-26 13:20:35,835 - app - INFO - 用户 admin1 正在查看个人资料页面。
2025-06-26 13:20:41,294 - app - INFO - 用户 admin1 正在查看个人资料页面。
2025-06-26 13:20:43,199 - app - INFO - 用户 admin1 正在查看个人资料页面。
2025-06-26 13:23:59,761 - app - INFO - 用户 admin1 成功加载首页。
2025-06-26 13:24:03,161 - app - INFO - 用户 admin1 已登出。
2025-06-26 13:24:15,933 - app - INFO - 新用户 admin2 (角色: ADMIN) 注册成功。
2025-06-26 13:24:15,953 - app - INFO - 用户 admin2 成功加载首页。
2025-06-26 13:27:04,778 - app - INFO - 用户 admin2 成功加载首页。
2025-06-26 13:29:53,328 - app - INFO - 用户 admin2 正在查看个人资料页面。
2025-06-26 13:30:04,161 - app - INFO - 用户 admin2 正在查看个人资料页面。
2025-06-26 13:30:48,311 - app - INFO - 用户 admin2 正在查看个人资料页面。
2025-06-26 13:30:49,829 - app - INFO - 用户 admin2 正在查看个人资料页面。
2025-06-26 13:30:51,480 - app - INFO - 用户 admin2 正在查看个人资料页面。
2025-06-26 13:30:52,244 - app - INFO - 用户 admin2 正在查看个人资料页面。
2025-06-26 13:35:26,855 - app - INFO - 用户 admin2 成功加载首页。
2025-06-26 13:36:38,844 - app - INFO - 用户 admin2 成功加载首页。
2025-06-26 13:37:53,132 - app - INFO - 用户 admin2 已登出。
2025-06-26 13:37:58,334 - app - INFO - 用户 employee_92_2 登录成功。
2025-06-26 13:37:58,348 - app - INFO - 用户 employee_92_2 成功加载首页。
2025-06-26 13:38:02,848 - app - INFO - 用户 employee_92_2 正在查看个人资料页面。
